apiVersion: v1
items:
- apiVersion: ols.openshift.io/v1alpha1
  kind: OLSConfig
  metadata:
    creationTimestamp: "2026-07-16T18:27:54Z"
    finalizers:
    - ols.openshift.io/finalizer
    generation: 1
    name: cluster
    resourceVersion: "2294033"
    uid: 2b85fe64-f27c-4c43-a4df-2b164cba9f03
  spec:
    llm:
      providers:
      - credentialsSecretRef:
          name: gemma-creds
        models:
        - contextWindowSize: 35000
          name: granite41-3b
          parameters:
            toolBudgetRatio: 0.5
        name: red_hat_openshift_ai
        type: rhoai_vllm
        url: http://granite41-3b-predictor.llm-serving.svc.cluster.local:8080/v1
    ols:
      conversationCache:
        postgres:
          maxConnections: 2000
          sharedBuffers: 256MB
        type: postgres
      defaultModel: granite41-3b
      defaultProvider: red_hat_openshift_ai
      deployment:
        api:
          replicas: 1
        console:
          replicas: 1
        dataCollector: {}
        database:
          replicas: 1
        mcpServer: {}
      introspectionEnabled: true
      logLevel: DEBUG
      maxIterations: 5
      userDataCollection: {}
    olsDataCollector:
      logLevel: INFO
  status:
    conditions:
    - lastTransitionTime: "2026-07-16T18:28:13Z"
      message: Ready
      observedGeneration: 1
      reason: Available
      status: "True"
      type: ConsolePluginReady
    - lastTransitionTime: "2026-07-29T14:51:05Z"
      message: Ready
      observedGeneration: 1
      reason: Available
      status: "True"
      type: CacheReady
    - lastTransitionTime: "2026-07-29T14:57:21Z"
      message: Ready
      observedGeneration: 1
      reason: Available
      status: "True"
      type: ApiReady
    overallStatus: Ready
kind: List
metadata:
  resourceVersion: ""
