apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    modelFormat: vLLM
    opendatahub.io/hardware-profile-name: nvidia-gpu
    opendatahub.io/hardware-profile-namespace: redhat-ods-applications
    opendatahub.io/model-type: generative
    openshift.io/display-name: granite-41-3b
    security.opendatahub.io/enable-auth: "false"
    serving.kserve.io/deploymentMode: Standard
  labels:
    opendatahub.io/dashboard: "true"
  name: granite-41-3b
  namespace: llm-serving
spec:
  predictor:
    automountServiceAccountToken: false
    deploymentStrategy:
      type: Recreate
    imagePullSecrets:
    - name: granite-41-3b
    maxReplicas: 1
    minReplicas: 1
    model:
      args:
      - --max-model-len=35000
      - --max-num-seqs=4
      - --gpu-memory-utilization=0.95
      - --enforce-eager
      - --enable-auto-tool-choice
      - --tool-call-parser=granite4
      modelFormat:
        name: vLLM
      name: ""
      resources:
        limits:
          cpu: "4"
          memory: 16Gi
          nvidia.com/gpu: "1"
        requests:
          cpu: "4"
          memory: 16Gi
          nvidia.com/gpu: "1"
      runtime: vllm-cuda-runtime
      storageUri: oci://registry.xphyrlab.net/markd/granite4.1-3b-llm:v1
    timeout: 30
