kind: Secret
apiVersion: v1
metadata:
  name: s3-secret
  namespace: llm-serving
stringData:
  AWS_ACCESS_KEY_ID: <your-access-key>
  AWS_DEFAULT_REGION: na
  AWS_S3_BUCKET: models
  AWS_S3_ENDPOINT: https://s3.example.com:9445
  AWS_SECRET_ACCESS_KEY: <your-secret-key>
type: Opaque
