kind: Secret
apiVersion: v1
metadata:
  name: s3-secret
  namespace: llm-serving
stringData:
  AWS_ACCESS_KEY_ID: 8tMRAZKZ2ro44nwInOgh
  AWS_DEFAULT_REGION: na
  AWS_S3_BUCKET: models
  AWS_S3_ENDPOINT: https://s3.xphyrlab.net:9445
  AWS_SECRET_ACCESS_KEY: 2asLPIgbPn8sPDB4T0mOsd4kl9iBy8e6Plr3rXRw
type: Opaque
